{{- include "silkstrand-agent.validateAuth" . -}}
{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "silkstrand-agent.fullname" . }}
  labels:
    {{- include "silkstrand-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.auth.installToken }}
  install-token: {{ .Values.auth.installToken | quote }}
  {{- end }}
  {{- if and .Values.auth.agentId .Values.auth.agentKey }}
  agent-id: {{ .Values.auth.agentId | quote }}
  agent-key: {{ .Values.auth.agentKey | quote }}
  {{- end }}
{{- end }}
